IF EXIST RELEASE.ID DEL *.OBJ
IF EXIST DEBUG.ID DEL *.OBJ
IF EXIST DREL.ID DEL *.OBJ
NMAKE DSTPMC-D.MAK
COPY STLIBPMC.H D:\BIN\H
COPY STPMCDD.LIB  D:\BIN\LIB 
DEL STPMCDD.LIB
ECHO CURRENT > DDEBUG.ID
DEL RELEASE.ID
DEL DEBUG.ID
DEL DREL.ID
