IF EXIST RELEASE.ID DEL *.OBJ
IF EXIST DDEBUG.ID DEL *.OBJ
IF EXIST DREL.ID DEL *.OBJ
NMAKE STPMC-D.MAK
COPY STLIBPMC.H D:\BIN\H
COPY STPMCD.LIB  D:\BIN\LIB 
DEL STPMCD.LIB
ECHO CURRENT > DEBUG.ID
DEL RELEASE.ID
DEL DREL.ID
DEL DDEBUG.ID
