REM ** Delete all old OBJ ***
IF EXIST RELEASE.ID DEL *.OBJ
IF EXIST DEBUG.ID DEL *.OBJ
IF EXIST DDEBUG.ID DEL *.OBJ
REM ** Create Release DLL ***
NMAKE DSTPMC-R.MAK
COPY STLIBPMC.H D:\BIN\H
COPY STPMCRD.LIB  D:\BIN\LIB 
DEL STPMCRD.LIB
REM ** Set latest build *****
ECHO CURRENT > DREL.ID
DEL RELEASE.ID
DEL DEBUG.ID
DEL DDEBUG.ID