IF EXIST DEBUG.ID DEL *.OBJ
IF EXIST DDEBUG.ID DEL *.OBJ
IF EXIST DREL.ID DEL *.OBJ
NMAKE STPMC-R.MAK
@COPY STLIBPMC.H D:\BIN\H
@COPY STPMCR.LIB  D:\BIN\LIB 
@DEL STPMCR.LIB
ECHO CURRENT > RELEASE.ID
@DEL DEBUG.ID
@DEL DREL.ID
@DEL DDEBUG.ID
