IF EXIST RELEASE.ID DEL *.OBJ
IF EXIST DEBUG.ID DEL *.OBJ
IF EXIST DREL.ID DEL *.OBJ
NMAKE DSTSTC-D.MAK
COPY STLIBSTC.H D:\BIN\H
COPY BTISAM.H D:\BIN\H
COPY STSTCDD.LIB  D:\BIN\LIB 
DEL STSTCDD.LIB
ECHO CURRENT > DDEBUG.ID
DEL RELEASE.ID
DEL DEBUG.ID
DEL DREL.ID
