REM ** Delete all old OBJ ***
IF EXIST RELEASE.ID DEL *.OBJ
IF EXIST DEBUG.ID DEL *.OBJ
IF EXIST DDEBUG.ID DEL *.OBJ
REM ** Create Release DLL ***
NMAKE DSTSTC-R.MAK
COPY STLIBSTC.H D:\BIN\H
COPY BTISAM.H D:\BIN\H
COPY STSTCRD.LIB  D:\BIN\LIB 
DEL STSTCRD.LIB
REM ** Set latest build *****
ECHO CURRENT > DREL.ID
DEL RELEASE.ID
DEL DEBUG.ID
DEL DDEBUG.ID